import matplotlib.pyplot as plt
import numpy as np
import os
from matplotlib.backends.backend_pdf import PdfPages

os.makedirs('visuals/128', exist_ok=True)

# 1. Action Frequencies (Losses)
actions = ['WATER', 'PASS', 'SOUTH', 'HARVEST', 'COLLECT_FERT', 'FEED']
us_loss = [99.7, 93.7, 119.9, 44.7, 37.6, 42.8]
opp_loss = [151.4, 148.3, 83.1, 58.8, 46.4, 44.7]

# 2. Net Cash Generated (Losses)
windows = ['Days 0-19', 'Days 20-24', 'Days 25-29']
us_cash = [43201, 26075, 24491]
opp_cash = [28700, 41506, 30876]

# 3. Revenue by Product (Losses)
products = ['Strawberry', 'Milk', 'Melon', 'Wheat', 'Wool', 'Fertilizer']
us_rev = [35594, 31165, 22293, 6029, 18408, 14491]
opp_rev = [61300, 33025, 14573, 20715, 12997, 11347]

width = 0.35
plt.style.use('ggplot')

with PdfPages('visuals/128/combined_charts.pdf') as pdf:
    # 1. Action Frequencies
    x = np.arange(len(actions))
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(x - width/2, us_loss, width, label='Us (Avg/Game)')
    ax.bar(x + width/2, opp_loss, width, label='Opponent (Avg/Game)')
    ax.set_ylabel('Frequency')
    ax.set_title('Top Actions: Us vs Opponent (In Losses - v128)')
    ax.set_xticks(x)
    ax.set_xticklabels(actions)
    ax.legend()
    plt.tight_layout()
    plt.savefig('visuals/128/chart_actions.png')
    pdf.savefig(fig)
    plt.close()

    # 2. Net Cash Generated
    x = np.arange(len(windows))
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(x - width/2, us_cash, width, label='Us')
    ax.bar(x + width/2, opp_cash, width, label='Opponent')
    ax.set_ylabel('Net Cash')
    ax.set_title('Net Cash Generated by Day Window (Losses - v128)')
    ax.set_xticks(x)
    ax.set_xticklabels(windows)
    ax.legend()
    plt.tight_layout()
    plt.savefig('visuals/128/chart_cash.png')
    pdf.savefig(fig)
    plt.close()

    # 3. Revenue by Product
    x = np.arange(len(products))
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(x - width/2, us_rev, width, label='Us')
    ax.bar(x + width/2, opp_rev, width, label='Opponent')
    ax.set_ylabel('Total Revenue')
    ax.set_title('Total Revenue by Key Product (Losses - v128)')
    ax.set_xticks(x)
    ax.set_xticklabels(products)
    ax.legend()
    plt.tight_layout()
    plt.savefig('visuals/128/chart_revenue.png')
    pdf.savefig(fig)
    plt.close()

print("Charts and combined PDF for v128 generated successfully in visuals/128/ folder.")
