import matplotlib.pyplot as plt
import numpy as np
import os
from matplotlib.backends.backend_pdf import PdfPages

os.makedirs('visuals', exist_ok=True)

actions = ['WATER', 'PASS', 'SOUTH', 'HARVEST', 'COLLECT_FERT', 'FEED']
us_loss = [98.6, 93.3, 119.8, 44.9, 37.9, 43.2]
opp_loss = [151.4, 148.3, 83.1, 58.8, 46.4, 44.8]

windows = ['Days 0-19', 'Days 20-24', 'Days 25-29']
us_cash = [43280, 26147, 23325]
opp_cash = [28831, 40460, 30097]

products = ['Strawberry', 'Milk', 'Melon', 'Wheat', 'Wool', 'Fertilizer']
us_rev = [32977, 32067, 22288, 5638, 19406, 14592]
opp_rev = [58836, 33058, 14430, 20698, 14373, 11197]

width = 0.35
plt.style.use('ggplot')

with PdfPages('visuals/combined_charts.pdf') as pdf:
    # 1. Action Frequencies
    x = np.arange(len(actions))
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(x - width/2, us_loss, width, label='Us (Avg/Game)')
    ax.bar(x + width/2, opp_loss, width, label='Opponent (Avg/Game)')
    ax.set_ylabel('Frequency')
    ax.set_title('Top Actions: Us vs Opponent (In Losses)')
    ax.set_xticks(x)
    ax.set_xticklabels(actions)
    ax.legend()
    plt.tight_layout()
    plt.savefig('visuals/chart_actions.png')
    pdf.savefig(fig)
    plt.close()

    # 2. Net Cash Generated
    x = np.arange(len(windows))
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(x - width/2, us_cash, width, label='Us')
    ax.bar(x + width/2, opp_cash, width, label='Opponent')
    ax.set_ylabel('Net Cash')
    ax.set_title('Net Cash Generated by Day Window (Losses)')
    ax.set_xticks(x)
    ax.set_xticklabels(windows)
    ax.legend()
    plt.tight_layout()
    plt.savefig('visuals/chart_cash.png')
    pdf.savefig(fig)
    plt.close()

    # 3. Revenue by Product
    x = np.arange(len(products))
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(x - width/2, us_rev, width, label='Us')
    ax.bar(x + width/2, opp_rev, width, label='Opponent')
    ax.set_ylabel('Total Revenue')
    ax.set_title('Total Revenue by Key Product (Losses)')
    ax.set_xticks(x)
    ax.set_xticklabels(products)
    ax.legend()
    plt.tight_layout()
    plt.savefig('visuals/chart_revenue.png')
    pdf.savefig(fig)
    plt.close()

print("Charts and combined PDF generated successfully in visuals/ folder.")
